# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import storage.image_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('filename', models.ImageField(storage=storage.image_storage.ImageStorage(), upload_to=b'')),
                ('mime', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
