# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='create',
            field=models.DateField(default=datetime.datetime(2018, 3, 22, 16, 21, 18, 284330, tzinfo=utc)),
        ),
    ]
