# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='postvisited',
            old_name='create',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='postvisited',
            old_name='update',
            new_name='update_at',
        ),
    ]
