# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180322_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create',
            field=models.DateField(default=datetime.datetime(2018, 3, 22, 20, 45, 22, 674318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(auto_now=True),
        ),
    ]
