# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('posts', '0002_auto_20180430_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(to='file.File'),
        ),
    ]
