# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(related_name='image', to='file.File'),
        ),
    ]
