# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180430_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='image', to='file.File'),
        ),
    ]
