# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180323_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
