# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('posts', '0006_auto_20180501_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='image', to='file.File'),
        ),
    ]
