# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import storage.image_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=storage.image_storage.ImageStorage(), upload_to=b'')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
